export const zodiacPeriods = {
  translated: {
    aries: "21 March - 19 April",
    taurus: "20 April - 20 May",
    gemini: "21 May - 20 June",
    cancer: "21 June - 22 July",
    leo: "23 July - 22 August",
    virgo: "23 August - 22 September",
    libra: "23 September - 22 October",
    scorpio: "23 October - 21 November",
    sagittarius: "22 November - 21 December",
    capricorn: "22 December - 19 January",
    aquarius: "20 January - 18 February",
    pisces: "19 February - 20 March",
  },
  original: {
    aries: "21 марта - 19 апреля",
    taurus: "20 апреля - 20 мая",
    gemini: "21 мая - 20 июня",
    cancer: "21 июня - 22 июля",
    leo: "23 июля - 22 августа",
    virgo: "23 августа - 22 сентября",
    libra: "23 сентября - 22 октября",
    scorpio: "23 октября - 21 ноября",
    sagittarius: "22 ноября - 21 декабря",
    capricorn: "22 декабря - 19 января",
    aquarius: "20 января - 18 февраля",
    pisces: "19 февраля - 20 марта",
  },
};
